services:
  instance:
    build: .
    restart: unless-stopped
    container_name: hoyolab-auto
    volumes:
      - ./config.json5:/app/config.json5:ro
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      TZ: America/Los_Angeles
      COOKIE_REFRESH_HOST: ""
    ports:
      - "3002:3002"